[package]
name = "conrogate-plugin-cors"
description = "Conrogate 官方跨域插件"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
conrogate-contract = { workspace = true }
conrogate-plugin = { workspace = true }
async-trait = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
