[package]
name = "conrogate-plugin-log"
description = "Conrogate 官方日志插件"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
conrogate-contract = { workspace = true }
conrogate-plugin = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
